
version: '2'
services:

  tledb:
    build:
      context: ../.
      dockerfile: /home/rtubio/repositories/com.github.karbontek/tledb/config/dockerfile.tledb
    networks:
      - nginx_network
      - db_network
    volumes:
      - static_volume:/opt/services/tledb/static
    depends_on:
      - mysqldb
      - rabbitmq

  nginx:
    build:
      context: ../.
      dockerfile: /home/rtubio/repositories/com.github.karbontek/tledb/config/dockerfile.nginx
    ports:
      - 8000:80
    depends_on:
      - tledb
    volumes:
      - static_volume:/opt/services/tledb/static
    networks:
      - nginx_network

  rabbitmq:
    image: rabbitmq:3
    networks:
      - db_network

  mysqldb:
    image: mysql:5.7
    env_file:
      - /home/rtubio/repositories/com.github.karbontek/tledb/.secrets/mysql.env
    networks:
      - db_network
    volumes:
      - db_vol:/var/lib/mysql

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  db_vol:
  static_volume:

