# Generated by Django 2.1.5 on 2019-01-09 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=24, unique=True, verbose_name='Identifier of the spacecraft that this TLE element models (line 0)')),
                ('timestamp', models.BigIntegerField(verbose_name='Timestamp with the update date for this TLE')),
                ('source', models.TextField(max_length=100, validators=[django.core.validators.URLValidator()], verbose_name='String that indicates the source of this TLE')),
                ('first_line', models.CharField(max_length=69, validators=[django.core.validators.RegexValidator(code='invalid_tle_line_1', message="Alphanumeric or '.-_' required", regex='^[a-zA-Z0-9.\\s-]{69}$')], verbose_name='First line of this TLE')),
                ('second_line', models.CharField(max_length=69, validators=[django.core.validators.RegexValidator(code='invalid_tle_line_2', message="Alphanumeric or '.-_' required", regex='^[a-zA-Z0-9.\\s-]{69}$')], verbose_name='Second line of this TLE')),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
    ]
