# Generated by Django 2.1.5 on 2019-01-13 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0003_auto_20190110_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tle',
            name='first_line',
            field=models.CharField(max_length=69, validators=[django.core.validators.RegexValidator(code='invalid_tle_line_1', message="Alphanumeric or '.-_' required", regex='^[a-zA-Z0-9.\\s-]{69}$')], verbose_name='L1'),
        ),
        migrations.AlterField(
            model_name='tle',
            name='identifier',
            field=models.CharField(max_length=24, unique=True, verbose_name='Spacecraft'),
        ),
        migrations.AlterField(
            model_name='tle',
            name='second_line',
            field=models.CharField(max_length=69, validators=[django.core.validators.RegexValidator(code='invalid_tle_line_2', message="Alphanumeric or '.-_' required", regex='^[a-zA-Z0-9.\\s-]{69}$')], verbose_name='L2'),
        ),
        migrations.AlterField(
            model_name='tle',
            name='source',
            field=models.TextField(max_length=100, validators=[django.core.validators.URLValidator()], verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='tle',
            name='timestamp',
            field=models.BigIntegerField(verbose_name='Timestamp'),
        ),
    ]
