name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Load Environment
      run: |
        source 'conf/paths.conf'
        echo "tledb_py_pkgs=$REQUIREMENTS_FILE" >> $GITHUB_ENV
        echo "tledb_gh_setup=$GH_SETUP" >> $GITHUB_ENV
        echo "tledb_coverage_rc=$GH_COVERAGE_CONF" >> $GITHUB_ENV
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r "$tledb_py_pkgs"
    - name: Setup Test Environment
      run: |
        bash "$tledb_gh_setup"
    - name: Run Tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd tledb && export __DJ_ENV='dev' && coverage run --rcfile="$tledb_coverage_rc" manage.py test && coveralls
