name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Load custom environment
      run: |
        bash 'conf/dev/gen-ghenv.sh'
        bash 'conf/dev/gen-ghenv.sh' >> $GITHUB_ENV
    - name: Install Dependencies
      run: |
        echo "$tledb_py_pkgs"
        python -m pip install --upgrade pip
        pip install -r conf/requirements.txt
    - name: Setup Test Environment
      run: |
        bash conf/dev/setup.sh
    - name: Run Tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd tledb
        export __DJ_DEVPROD='dev'
        coverage run --rcfile='../conf/dev/coverage.conf' manage.py test
        coveralls
